dataset:
  train_folder: "/workspace/new_datasets/LibriTTS_R-360-Train-new"
  val_folder: "/workspace/new_datasets/LibriTTS_R-Dev-new"
  test_folder: "/workspace/new_datasets/LibriTTS_R-Test-new"
  max_files: -1

audio:
  sampling_rate: 16000

vocab:
  phoneme_map: {'ʌ': 'ʌ', '': 'h#', 'm': 'm', 'ə': 'ə', 'h#': 'h#', 'θ': 'θ', 'ɑːɹ': 'ɑːɹ', 'eɪ': 'eɪ', 'ɔː': 'ɔː', 'j': 'j', 'ʊɹ': 'ʊ', 'l': 'l', 'tʃ': 'tʃ', 'ɚ': 'ɚ', 'z': 'z', 'əl': 'əl', 'aɪɚ': 'aɪ', 'ɹ': 'ɹ', 'p': 'p', 't': 't', 'd': 'd', 'ɾ': 'ɾ', 'ᵻ': 'ᵻ', 'iː': 'iː', 'oʊ': 'oʊ', 'ɛ': 'ɛ', 'ɑː': 'ɑː', 'dʒ': 'dʒ', 'ɔ': 'ɔ', 's': 's', 'r': 'ɹ', 'ɔɪ': 'ɔɪ', 'w': 'w', 'ð': 'ð', 'aɪ': 'aɪ', 'ɪɹ': 'ɪɹ', 'h': 'h', 'æ': 'æ', 'n': 'n', 'b': 'b', 'aɪə': 'aɪ', 'v': 'v', 'aʊ': 'aʊ', 'ɜː': 'ɜː', 'ɐ': 'ɐ', 'k': 'k', 'uː': 'uː', 'ɪ': 'ɪ', 'f': 'f', 'ɛɹ': 'ɛɹ', 'ŋ': 'ŋ', 'ʔ': 'ʔ', 'ɔːɹ': 'ɔːɹ', 'n̩': 'n', 'iə': 'iə', 'ɑ̃': 'ɑː', 'ʃ': 'ʃ', 'ʊ': 'ʊ', 'ɡ': 'ɡ', 'ʒ': 'ʒ', 'i': 'i'}
  unk_token: "[UNK]"
  pad_token: "[PAD]"
  delimiter_token: "|"

model:
  pretrained_model: "facebook/wav2vec2-base"
  freeze_feature_extractor: True
  vocab_size: null

training:
  multi_gpu: True
  output_dir: "/workspace/checkpoints"
  per_device_train_batch_size: 64
  gradient_accumulation_steps: 1
  evaluation_strategy: "steps"
  gradient_checkpointing: True
  fp16: True
  epochs: 100
  patience: 5
  save_steps: 1000
  eval_steps: 1000
  logging_steps: 100
  learning_rate: 3e-5
  warmup_steps: 2000
  save_total_limit: 3
  load_best_model_at_end: True
